@echo off
setlocal enabledelayedexpansion

:: Set Java 17 home
set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.15.6-hotspot"
set "PATH=%JAVA_HOME%\bin;%PATH%"
set "GRADLE_OPTS=-Dorg.gradle.java.home=%JAVA_HOME% -Dfile.encoding=UTF-8"

:: Print environment information
echo =============================================
echo   BUILD ENVIRONMENT
echo =============================================
echo Java Version:
java -version 2>&1
echo.
echo JAVA_HOME = %JAVA_HOME%
echo GRADLE_OPTS = %GRADLE_OPTS%
echo =============================================
echo.

:: Clean Gradle and build directories
echo [1/4] Cleaning build directories...
if exist .gradle rmdir /s /q .gradle
if exist build rmdir /s /q build
if exist run rmdir /s /q run
if exist .idea rmdir /s /q .idea

:: Create/update Gradle wrapper
echo [2/4] Setting up Gradle wrapper...
if not exist gradle\wrapper mkdir gradle\wrapper

:: Download gradle-wrapper.jar if it doesn't exist
if not exist gradle\wrapper\gradle-wrapper.jar (
    echo Downloading gradle-wrapper.jar...
    powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/gradle/gradle/raw/v8.1.1/gradle/wrapper/gradle-wrapper.jar', 'gradle/wrapper/gradle-wrapper.jar')" || (
        echo Failed to download gradle-wrapper.jar
        exit /b 1
    )
)

:: Create/update gradle-wrapper.properties
echo # DO NOT EDIT - Generated by clean_and_build.bat > gradle\wrapper\gradle-wrapper.properties
echo distributionBase=GRADLE_USER_HOME>> gradle\wrapper\gradle-wrapper.properties
echo distributionPath=wrapper/dists>> gradle\wrapper\gradle-wrapper.properties
echo distributionUrl=https\://services.gradle.org/distributions/gradle-8.1.1-bin.zip>> gradle\wrapper\gradle-wrapper.properties
echo networkTimeout=10000>> gradle\wrapper\gradle-wrapper.properties
echo validateDistributionUrl=true>> gradle\wrapper\gradle-wrapper.properties
echo zipStoreBase=GRADLE_USER_HOME>> gradle\wrapper\gradle-wrapper.properties
echo zipStorePath=wrapper/dists>> gradle\wrapper\gradle-wrapper.properties

:: Create gradlew.bat if it doesn't exist
if not exist gradlew.bat (
    echo @echo off > gradlew.bat
    echo setlocal enabledelayedexpansion >> gradlew.bat
    echo set JAVA_HOME=%%~dp0jdk-17.0.15.6-hotspot >> gradlew.bat
    echo if not exist "!JAVA_HOME!" set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.15.6-hotspot" >> gradlew.bat
    echo set PATH=!JAVA_HOME!\bin;%%PATH%% >> gradlew.bat
    echo set GRADLE_OPTS=-Dorg.gradle.java.home=!JAVA_HOME! -Dfile.encoding=UTF-8 >> gradlew.bat
    echo "!JAVA_HOME!\bin\java" -Dorg.gradle.appname=gradlew -classpath "%%~dp0gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain %%* >> gradlew.bat
)

:: Verify Gradle wrapper
echo [3/4] Verifying Gradle wrapper...
call gradlew --version
if %ERRORLEVEL% neq 0 (
    echo Failed to verify Gradle wrapper
    exit /b 1
)

:: Run the build
echo [4/4] Starting build...
echo Running build...
call gradlew clean build --stacktrace --info

if %ERRORLEVEL% EQU 0 (
    echo.
    echo Build completed successfully!
    echo You can find the built files in the build/libs directory.
    exit /b 0
) else (
    echo.
    echo Build failed with error code %ERRORLEVEL%
    echo Check the output above for details.
    exit /b %ERRORLEVEL%
)
