@echo off
setlocal enabledelayedexpansion

:: Set Java 17 Home
set "JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-17.0.15.6-hotspot"
set "PATH=!JAVA_HOME!\bin;%PATH%"

:: Set Gradle version
set GRADLE_VERSION=7.6.1

echo Updating Gradle wrapper to version %GRADLE_VERSION%...

:: Create gradle wrapper directory if it doesn't exist
if not exist "gradle\wrapper" mkdir "gradle\wrapper"

:: Create gradle wrapper properties
(
    echo distributionBase=GRADLE_USER_HOME
    echo distributionPath=wrapper/dists
    echo distributionUrl=https\://services.gradle.org/distributions/gradle-%GRADLE_VERSION%-bin.zip
    echo zipStoreBase=GRADLE_USER_HOME
    echo zipStorePath=wrapper/dists
) > gradle\wrapper\gradle-wrapper.properties

:: Download gradle-wrapper.jar directly
if not exist "gradle\wrapper\gradle-wrapper.jar" (
    echo Downloading gradle-wrapper.jar...
    curl -L -o gradle\wrapper\gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v%GRADLE_VERSION%/gradle/wrapper/gradle-wrapper.jar
    if !ERRORLEVEL! NEQ 0 (
        echo Failed to download gradle-wrapper.jar
        exit /b !ERRORLEVEL!
    )
)

:: Create gradlew.bat
(
    echo @if "%%DEBUG%%" == "" @echo off
    echo @rem ##########################################################################
    echo @rem
    echo @rem  Gradle startup script for Windows
    echo @rem
    echo @rem ##########################################################################
    echo.
    echo @rem Set local scope for the variables with windows NT shell
    echo if "%%OS%%"=="Windows_NT" setlocal
    echo.
    echo set DIRNAME=%%~dp0
    echo if not "%%DIRNAME%%" == "" set DIRNAME=%%DIRNAME:~0,-1%%
    echo set APP_HOME=%%DIRNAME%%
    echo.
    echo @rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
    echo set DEFAULT_JVM_OPTS="-Xmx64m" "-Xms64m"
    echo.
    echo @rem Find java.exe
    echo if defined JAVA_HOME goto findJavaFromJavaHome
    echo.
    echo set JAVA_EXE=java.exe
    echo %%~sdp0\jre\bin\java.exe -version ^>nul 2^>^&1
    echo if "%%ERRORLEVEL%%" == "0" goto init
    echo.
    echo echo.
    echo echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
    echo echo.
    echo echo Please set the JAVA_HOME variable in your environment to match the
    echo echo location of your Java installation.
    echo.
    echo goto fail
    echo.
    echo :findJavaFromJavaHome
    echo set JAVA_HOME=%%JAVA_HOME:"=%%
    echo set JAVA_EXE=%%JAVA_HOME%%\bin\java.exe
    echo.
    echo if exist "%%JAVA_EXE%%" goto init
    echo.
    echo echo.
    echo echo ERROR: JAVA_HOME is set to an invalid directory: %%JAVA_HOME%%
    echo echo.
    echo echo Please set the JAVA_HOME variable in your environment to match the
    echo echo location of your Java installation.
    echo.
    echo goto fail
    echo.
    echo :init
    echo @rem Get command-line arguments, handling Windows variants
    echo.
    echo if not "%%OS%%" == "Windows_NT" goto win9xME_args
    echo.
    echo :win9xME_args
    echo @rem Slurp the command line arguments.
    echo set CMD_LINE_ARGS=
    echo set _SKIP=2
    echo.
    echo :win9xME_args_slurp
    echo if "x%%~1"=="x" goto execute
    echo.
    echo set CMD_LINE_ARGS=%%*
    echo.
    echo :execute
    echo @rem Setup the command line
    echo.
    echo set CLASSPATH=%%APP_HOME%%\gradle\wrapper\gradle-wrapper.jar
    echo.
    echo @rem Execute Gradle
    echo "%%JAVA_EXE%%" %%DEFAULT_JVM_OPTS%% %%JAVA_OPTS%% %%GRADLE_OPTS%% "-Dorg.gradle.appname=gradlew" -classpath "%%CLASSPATH%%" org.gradle.wrapper.GradleWrapperMain %%CMD_LINE_ARGS%%
    echo.
    echo :end
    echo @rem End local scope for the variables with windows NT shell
    echo if "%%OS%%"=="Windows_NT" endlocal
    echo.
    echo :fail
    echo rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
    echo rem the _cmd.exe /c_ return code!
    echo if not "" == "%%GRADLE_EXIT_CONSOLE%%" exit 1
    echo exit /b 1
) > gradlew.bat

:: Create gradlew for Unix-like systems
(
    echo #!/bin/sh
    echo ##############################################################################
    echo "#"
    echo "#   Gradle startup script for POSIX generated by Gradle.
    echo "#"
    echo "#   Important for running:
    echo "#   (1) You need a POSIX-compliant shell to run this script.
    echo "#   (2) If you run this script using the sh/path/to/gradlew, then this
    echo "#       script will find and use gradle from the current directory.
    echo "#   (3) If you run this script using the full path to the script, then the
    echo "#       script will find and use gradle from the current directory.
    echo "#"
    echo ##############################################################################
    echo
    echo # Attempt to set APP_HOME
    echo
    echo # Resolve links: $0 may be a link
    echo PRG="$0"
    echo # Need this for relative symlinks.
    echo while [ -h "$PRG" ] ; do
    echo     ls=`ls -ld "$PRG"`
    echo     link=`expr "$ls" : '.*-> \(.*\)$'`
    echo     if expr "$link" : '/.*' > /dev/null; then
    echo         PRG="$link"
    echo     else
    echo         PRG=`dirname "$PRG"`"/$link"
    echo     fi
    echo done
    echo SAVED="`pwd`"
    echo cd "`dirname \"$PRG\"`/" >&2
    echo APP_HOME="`pwd -P`"
    echo cd "$SAVED" >/dev/null
    echo
    echo # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
    echo DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
    echo
    echo # Use the maximum available, or set MAX_FD != -1 to use that value.
    echo MAX_FD="maximum"
    echo
    echo warn () {
    echo     echo "$*"
    echo }
    echo
    echo die () {
    echo     echo
    echo     echo "$*"
    echo     echo
    echo     exit 1
    echo }
    echo
    echo # OS specific support (must be 'true' or 'false').
    echo cygwin=false
    echo msys=false
    echo darwin=false
    echo nonstop=false
    echo case "`uname`" in
    echo   CYGWIN* )
    echo     cygwin=true
    echo     ;;
    echo   Darwin* )
    echo     darwin=true
    echo     ;;
    echo   MINGW* )
    echo     msys=true
    echo     ;;
    echo   NONSTOP* )
    echo     nonstop=true
    echo     ;;
    echo esac
    echo
    echo CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
    echo
    echo # Determine the Java command to use to start the JVM.
    echo if [ -n "$JAVA_HOME" ] ; then
    echo     if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
    echo         # IBM's JDK on AIX uses strange locations for the executables
    echo         JAVACMD="$JAVA_HOME/jre/sh/java"
    echo     else
    echo         JAVACMD="$JAVA_HOME/bin/java"
    echo     fi
    echo     if [ ! -x "$JAVACMD" ] ; then
    echo         die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
    echo
    echo Please set the JAVA_HOME variable in your environment to match the
    echo location of your Java installation."
    echo     fi
    echo else
    echo     JAVACMD="java"
    echo     which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
    echo
    echo Please set the JAVA_HOME variable in your environment to match the
    echo location of your Java installation."
    echo fi
    echo
    echo # Increase the maximum file descriptors if we can.
    echo if [ "$cygwin" = "false" -a "$darwin" = "false" -a "$nonstop" = "false" ] ; then
    echo     MAX_FD_LIMIT=`ulimit -H -n`
    echo     if [ $? -eq 0 ] ; then
    echo         if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
    echo             MAX_FD="$MAX_FD_LIMIT"
    echo         fi
    echo         ulimit -n $MAX_FD
    echo         if [ $? -ne 0 ] ; then
    echo             warn "Could not set maximum file descriptor limit: $MAX_FD"
    echo         fi
    echo     else
    echo         warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    echo     fi
    echo fi
    echo
    echo # For Darwin, add options to specify how the application appears in the dock
    echo if $darwin; then
    echo     GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
    echo fi
    echo
    echo # For Cygwin, switch paths to Windows format before running java
    echo if $cygwin ; then
    echo     APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    echo     CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    echo     JAVACMD=`cygpath --unix "$JAVACMD"`
    echo
    echo     # We build the pattern for arguments to be converted via cygpath
    echo     ROOTDIRSRAW=`find -L / -maxdepth 1 -mindepth 1 -type d 2>/dev/null`
    echo     SEP=""
    echo     for dir in $ROOTDIRSRAW ; do
    echo         ROOTDIRS="$ROOTDIRS$SEP$dir"
    echo         SEP="|"
    echo     done
    echo     OURCYGPATTERN="^(($ROOTDIRS))"
    echo     # Add a user-defined pattern to the cygpath arguments
    echo     if [ "$GRADLE_CYGPATTERN" != "" ] ; then
    echo         OURCYGPATTERN="$OURCYGPATTERN|($GRADLE_CYGPATTERN)"
    echo     fi
    echo     # Now convert the arguments - kludge to limit ourselves to /bin/sh
    echo     i=0
    echo     for arg in "$@" ; do
    echo         CHECK=`echo "$arg"|egrep -c "$OURCYGPATTERN" -`
    echo         CHECK2=`echo "$arg"|egrep -c "^-"`                                 ### Determine if an option
    echo
    echo         if [ $CHECK -ne 0 ] && [ $CHECK2 -eq 0 ] ; then                    ### Added a condition
    echo             eval `echo args$i`=`cygpath --path --ignore --mixed "$arg"`
    echo         else
    echo             eval `echo args$i`=\"$arg\"
    echo         fi
    echo         i=$((i+1))
    echo     done
    echo     case $i in
    echo         (0) set -- ;;
    echo         (1) set -- "$args0" ;;
    echo         (2) set -- "$args0" "$args1" ;;
    echo         (3) set -- "$args0" "$args1" "$args2" ;;
    echo         (4) set -- "$args0" "$args1" "$args2" "$args3" ;;
    echo         (5) set -- "$args0" "$args1" "$args2" "$args3" "$args4" ;;
    echo         (6) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" ;;
    echo         (7) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" ;;
    echo         (8) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" ;;
    echo         (9) set -- "$args0" "$args1" "$args2" "$args3" "$args4" "$args5" "$args6" "$args7" "$args8" ;;
    echo     esac
    echo fi
    echo
    echo # Escape application args
    echo save () {
    echo     for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo     echo " "
    echo }
    echo APP_ARGS=$(save "$@")
    echo
    echo # Collect all arguments for the java command, following the shell quoting and substitution rules
    echo eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \"\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"
    echo
    echo exec "$JAVACMD" "$@"
) > gradlew

:: Make gradlew executable on Unix-like systems
attrib -r gradlew >nul 2>&1 || true

echo Gradle wrapper files have been created successfully.
echo.
echo Please run: gradlew --version
echo.

endlocal
